version: "3"
services:
  went: &went
    build: .
    volumes:
      - .:/went
    working_dir: /went
    cap_add:
      - ALL
    security_opt:
      - seccomp:unconfined
  test:
    <<: *went
    command: >
      bash -c '
        make
        make test
      '
