name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v1

      - name: install go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15.3'

      - name: test
        run: make test
